var express = require('express');
let router = express.Router({ mergeParams: true });
// const puppeteer = require('puppeteer');
const fs = require('fs');
var MiddleWare = require("../utils/middleware");
var MetaModel = require('../models/models').MetaModel;

router.post("/", MiddleWare.checkBodyId, async function (req, res) {
    // try{
    //     var metaData = await MetaModel().find({ _id: req.body.family_id }, { "pin": 0 }).lean();
    //     if (metaData.length == 0) {
    //         throw new Error('No Session');
    //     }
    //     // product:'firefox'
    //     const browser = await puppeteer.launch({ defaultViewport: null, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
    //     const page = await browser.newPage()
    //     await page.setViewport({ width: 1280, height: 800 })
    //     await page.setDefaultNavigationTimeout(0);
    
    //     // let curSiteUrl = `${req.headers['x-forwarded-proto']}://${req.headers['x-forwarded-host']}/`;
    //     let curSiteUrl = "https://blineqa.netlify.app/";
    //     const cookie = {
    //         name: 'puppy_bypass',
    //         value: 'jai_pass',
    //         url: curSiteUrl,
    //     }
    //     await page.setCookie(cookie);
    //     await page.goto(curSiteUrl+'app/'+metaData[0].surname);
    //     await page.waitForSelector(".puppy-tree");

    //     await page.evaluate(({metaData}) => {
    //         let dom = document.querySelector('.foot');
    //         dom.parentNode.removeChild(dom);
    //         let titleBar = document.querySelector('.tree-titlebar');
    //         titleBar.parentNode.removeChild(titleBar);
    
    //         let test = document.querySelector('#download-pic');
    //         test.parentNode.removeChild(test);
    
    //         let app = document.querySelector('#app');
    //         app.removeAttribute("style");

    //         let puppyTree = document.querySelector('.puppy-tree');
    //         puppyTree.setAttribute("style", "padding-top: 70px;display: flex;flex-direction: column;");
    //         let footerHtml = '<h6 style="color:white;">Generated by <span style="color:red;font-weight:bold">www.bloodline.ga</span></h6>';
    //         let center = document.createElement('center');
    //         center.innerHTML = footerHtml;
    //         center.setAttribute("style", "background-color:black;padding:10px;margin-bottom:0px");
    //         puppyTree.appendChild(center);

    //         let headerHtml =  '<h4 style="color:indianred;margin-bottom:20px;margin-top:0px !important">'+metaData[0].title+'</h4>';
    //         let center2 = document.createElement('center');
    //         center2.innerHTML = headerHtml;
    //         puppyTree.prepend(center2);
    //     }, {metaData});
    //     // let bodyHTML = await page.evaluate(() => document.body.innerHTML);
    //     // fs.writeFileSync('jai.html', bodyHTML);

    //     let img = await page.screenshot({ encoding: "base64", fullPage: true })
    //     await browser.close()
    //     res.send(img);
    // }
    // catch(err){
    //     console.log(err);
    //     res.status(502).send(err);
    // }
});

module.exports = router;  